### ISSUE TITLE
Do not say " By karanpatel " in the desc if you said it is a few edits by you in the code

### ISSUE THREAD

**Issue by KielKing** [karanpatel567/Spawner#2]
Do not say " By karanpatel " in the desc if you said it is a few edits by you in the code, please, credit the original maker

**Comment by RishiP2004** [comment]
I agree, please give proper credit to the maker of this plugin.

**Comment by karanpatel567** [comment]
Thing is it didn't say who made it, not even on the Plugin.yml

**Comment by RishiP2004** [comment]
author on plugin.yml is you (clearly false), and it says “made by karanpatel81” on description. Please change ASAP
